### ISSUE TITLE
Add eslint-plugin-arithmetic

### ISSUE THREAD

**Issue by Manu1400** [JonnyBurger/eslint-config#2]

**Comment by JonnyBurger** [comment]
Hi! Thanks for the idea!

Since I use my config for many projects, I don't want to introduce my plugin to all of them at once, since changes the actual code.

You can of course use the plugin with the preset together by adding it to your config: 

```js
{
    "extends": ["@jonny"],
    "plugins": ["arithemetic"]
}
```
